version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:z
  redis:
    image: redis
    volumes:
      - ./tmp/data:/data
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
  web:
    build: .
    command: bundle exec rails s -p 3002 -b "0.0.0.0"
    volumes:
      - .:/myapp
    ports:
      - "3002:3002"
    depends_on:
      - db
      - redis
